version: '3.3'

services:
  altai:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT-3000}:3000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
      - /usr/src/app/.husky
    environment:
      - API_KEY=${API_KEY-very_weak_api_key}
      - BASE_URL=http://altai:3000
      - MONGODB_URI=mongodb://mongodb:27017/altai
    depends_on:
      - mongodb
    networks:
      - ai-app

  cron-app:
    build:
      context: cron
      dockerfile: Dockerfile
    command: node index.js
    environment:
      - BASE_URL=http://altai:3000
      - API_KEY=${API_KEY-very_weak_api_key}
    networks:
      - ai-app

  mongodb:
    image: mongo:4.4-bionic
    volumes:
      - assessment-db:/data/db
    ports:
      - 27019:27017
    networks:
      - ai-app

networks:
  ai-app:
    driver: bridge

volumes:
  assessment-db:
