version: '3.3'

services:
  assessment-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
      - /usr/src/app/.husky
    env_file:
      - .env.development
    depends_on:
      - mongodb
    networks:
      - ai-app

  cron-app:
    build:
      context: cron
      dockerfile: Dockerfile
    command: node index.js
    env_file:
      - .env.development
    networks:
      - ai-app

  mongodb:
    image: mongo:4.4-bionic
    volumes:
      - assessment-db:/data/db
    ports:
      - 27017:27017
    networks:
      - ai-app

networks:
  ai-app:
    driver: bridge

volumes:
  assessment-db:
